export const taskList = [
  {
    id: 1,
    taskName: "I will do gym",
    dueDate: "2025-01-18",
    status: "Todo",
    category: "Personal",
  },
  {
    id: 2,
    // taskName:
    //   "Watch a movie with family this weekend to relax and unwind together",
    taskName: "I will do yoga and gym",
    dueDate: "2025-01-30",
    status: "Todo",
    category: "Work",
  },
  {
    id: 3,
    taskName: "Attend team meeting",
    dueDate: "2025-01-17",
    status: "Todo",
    category: "Personal",
  },
  {
    id: 12,
    taskName: "Organize workspace",
    dueDate: "2025-01-29",
    status: "Completed",
    category: "Personal",
  },
  {
    id: 13,
    taskName: "Plan team event",
    dueDate: "2025-01-16",
    status: "InProgress",
    category: "Work",
  },
  {
    id: 14,
    taskName: "Finish home renovation",
    dueDate: "2025-01-13",
    status: "InProgress",
    category: "Personal",
  },
  {
    id: 17,
    taskName: "Organize family dinner",
    dueDate: "2025-01-13",
    status: "InProgress",
    category: "Personal",
  },
  {
    id: 18,
    taskName: "Finish assignment",
    dueDate: "2025-01-30",
    status: "InProgress",
    category: "Personal",
  },
  {
    id: 20,
    taskName: "Team building workshop",
    dueDate: "2025-01-19",
    status: "Completed",
    category: "Work",
  },
  {
    id: 25,
    taskName: "Clean the house",
    dueDate: "2025-01-24",
    status: "InProgress",
    category: "Personal",
  },
];
